### ISSUE TITLE
 Pipelined write feature enabled example is wrong

### ISSUE THREAD

**Issue by thenamehasbeentake** [shenmingik/note#1]
In file rocksdb/FAQ/rocksdb特性.md 写特性  pipeline写入
~~opt.create_missing_column_families = true;~~         :      No
Options.enable_pipelined_write=true                            :      Yes

**Comment by shenmingik** [comment]
感谢，写文档的时候粘错代码了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月13日(星期四) 下午4:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [shenmingik/note]  Pipelined write feature enabled example is wrong (Issue #1)





 
In file rocksdb/FAQ/rocksdb特性.md 写特性  pipeline写入
 opt.create_missing_column_families = true;         :      No
 Options.enable_pipelined_write=true                            :      Yes
